In [1]:
import numpy as np
np.array(["xfsdg",3,4])

array(['xfsdg', '3', '4'], dtype='<U5')

In [3]:
l=[4,5,6,7]
type(l)

list

In [4]:
np.array(l)

array([4, 5, 6, 7])

In [5]:
type(np.array(l))

numpy.ndarray

In [6]:
np.array([3,4,5,6,"dfg",True])# hetrogeneous numpy array; (dtype='<U11')string takes more variable that's why it typecast each element into a string

array(['3', '4', '5', '6', 'dfg', 'True'], dtype='<U11')

In [ ]:
#Upcasting:

In [7]:
np.array([1, 2, 3.0])

array([1., 2., 3.])

In [8]:
n=np.array([1, 2, 3.0])
n.shape

(3,)

In [10]:
n.ndim

1

In [ ]:
#two dimensions

In [11]:
 np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [ ]:
#minimum dimensions 2:

In [12]:
np.array([1,2,3], ndmin=3)#ndmin=3 : array inside array inside array

array([[[1, 2, 3]]])

In [ ]:
#dtype

In [15]:
np.array([1,2,3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
#Data-type consisting of more than one element:

In [16]:
x = np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')])# tuples inside a list
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [17]:
x[0]

(1, 2)

In [18]:
x[0][0]

1

In [19]:
type(x[0][0])

numpy.int16

In [20]:
type(x[1][0])

numpy.int16

In [21]:
type(x[0][1])

numpy.int64

In [22]:
type(np.array([3,4,5,6],dtype=np.int8)[0])

numpy.int8

In [23]:
type(np.array([3,4,5,6],dtype=np.float)[0])

numpy.float64

In [26]:
 np.array([[1, 2], [4, 7]])[1][1]

7

In [28]:
 np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [29]:
type( np.array([[1, 2], [3, 4]]))

numpy.ndarray

In [27]:
np.mat(np.array([[1, 2], [3, 4]]))

matrix([[1, 2],
        [3, 4]])

In [30]:
type(np.mat(np.array([[1, 2], [3, 4]])))

numpy.matrixlib.defmatrix.matrix

In [31]:
m=np.mat(np.array([[1, 2], [3, 4]]))

In [32]:
np.array(m)

array([[1, 2],
       [3, 4]])

In [33]:
np.mat('1 2; 3 4')

matrix([[1, 2],
        [3, 4]])

# numpy.asarray

In [ ]:
#Convert the input to an array.

In [ ]:
#Convert a list into an array:

In [35]:
np.asarray([1,2,3,4])

array([1, 2, 3, 4])

In [36]:
type(np.asarray([1,2,3,4]))

numpy.ndarray

In [37]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [38]:
type(np.asanyarray([1,2,3,4,5]))

numpy.ndarray

In [40]:
m=np.mat([1,2,3,4,5])
m

matrix([[1, 2, 3, 4, 5]])

In [48]:
np.asanyarray([1, 2, 3, 4, 5]) is m

False

In [44]:
#as anyarray will try to convert some data into nd-array,if the data is not available in the form of array

In [ ]:
# difference between asarray and asanyarray
# asarray convert every thing into nd-array, whereas asanyarray will try to convert your data iff my data set is not available in any form of array

In [41]:
np.asanyarray(m)

matrix([[1, 2, 3, 4, 5]])

In [43]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [42]:
type(np.asanyarray(m))

numpy.matrixlib.defmatrix.matrix

In [45]:
a = [1, 2]
np.asanyarray(a)

array([1, 2])

In [46]:
a = np.matrix([1, 2])
a

matrix([[1, 2]])

In [47]:
np.asanyarray([1,2]) is a

False

In [49]:
#numpy.copy (deep copy and shallow copy)

In [50]:
a=np.array([1,2,3,4,])
a

array([1, 2, 3, 4])

In [ ]:
#sitiuation 1

In [51]:
b=a # Shallow copy:=Shallow Copy. A shallow copy creates a new object which stores the reference of the original elements. 

In [52]:
b

array([1, 2, 3, 4])

In [54]:
b[0]=4324

In [55]:
b

array([4324,    2,    3,    4])

In [56]:
a

array([4324,    2,    3,    4])

In [57]:
# situation 2

In [58]:
c=np.array(a,copy=True)# Deep copy:=  A deep copy creates a new object and recursively adds the copies of nested objects present in the original

In [59]:
c

array([4324,    2,    3,    4])

In [60]:
c[0]=1212


In [61]:
c

array([1212,    2,    3,    4])

In [62]:
a

array([4324,    2,    3,    4])

In [63]:
a=np.array([1,2,3,4,5])

In [64]:
c=np.array(a)

In [65]:
c

array([1, 2, 3, 4, 5])

In [66]:
c[0]=423

In [68]:
c

array([423,   2,   3,   4,   5])

In [70]:
id(c[0])

2722550081216

In [69]:
a

array([1, 2, 3, 4, 5])

In [73]:
id(a[0])

2722550081264

In [83]:
#Create an array x, with a reference y and a copy z:

In [85]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [86]:
y=x

In [87]:
z = np.copy(x)

In [88]:
y[0] = 100
x

array([100,   2,   3])

In [89]:
x

array([100,   2,   3])

In [90]:
id(x[0])

2722550081672

In [91]:
id(y[0])

2722550081696

In [92]:
id(x) 

2722551133968

In [93]:
id(y)

2722551133968

In [74]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [76]:
a=np.mat([1,2,3,4])
a

matrix([[1, 2, 3, 4]])

In [77]:
a=np.array([1,2,3,4], ndmin=5)
a

array([[[[[1, 2, 3, 4]]]]])

In [82]:
np.array([[1,2],[4,5]])


array([[1, 2],
       [4, 5]])

# numpy.fromfunction

In [94]:
#Construct an array by executing a function over each coordinate.

In [96]:
np.fromfunction(lambda i,j:i==j,(3,3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [97]:
np.fromfunction(lambda i,j:i*j,(3,3), dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [98]:
np.fromfunction(lambda i,j:i/j,(3,3), dtype=int)

C:\Users\SBCS\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\SBCS\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [100]:
np.fromfunction(lambda i,j,k:i*j*k,(4,3,3), dtype=int)# 4 array of size (3*3)

array([[[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  1,  2],
        [ 0,  2,  4]],

       [[ 0,  0,  0],
        [ 0,  2,  4],
        [ 0,  4,  8]],

       [[ 0,  0,  0],
        [ 0,  3,  6],
        [ 0,  6, 12]]])

In [102]:
np.fromfunction(lambda i,j,k,m:i*j*k*m,(4,3,2,2), dtype=int)

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 3]],

        [[0, 0],
         [0, 6]]]])